server:
  port: 7900
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth # Load-balanced URI via Eureka
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
            - AddJwtClaimsToHeader

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/