server:
  port: 7900
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: user-profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
jwt:
  secret: j^pEzRHYX@TDzuiJ4asZ!gF9MxrQ3Gx*H@A!7MC!XKWAM8n6h*7Lvc$DyhWFSrAw5fzGrG4hSPPynZnd2DKLbP*zcxMb@JqwM#ttQ6Lphg*eaRtD$o*Zo!tLLVqpvUVG