server:
  port: 7900
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: user-profile-service
          uri: http://profile-service:8082
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
            - AddJwtClaimsToHeader